### ISSUE TITLE
TypeError: currentValue.trim is not a function

### ISSUE THREAD

**Issue by kiikoh** [TomPrograms/construct-url#1]
TypeError: currentValue.trim is not a function
    at module.exports (/home/kiko/Projects/ic-calculator/node_modules/construct-url/index.js:101:33)
    at /home/kiko/Projects/ic-calculator/server.js:11:14
    at Layer.handle [as handle_request] (/home/kiko/Projects/ic-calculator/node_modules/express/lib/router/layer.js:95:5)

Passed in a number to queryParams.

Fixed by converting number to String before running.
Example:
`queryParams: {
			apikey: consumerKey,
			symbol: req.query.symbol,
			strikeCount: String(7),
		},`

**Comment by TomPrograms** [comment]
Sorry this took so long. I missed this issue. Hopefully it should be fixed now.
